#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# 2600net IRC MCP Server — Installer
# Completely independent of the Claude IRC Bot installation.
# Run as root: sudo bash install_mcp.sh
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}[*]${RESET} $*"; }
success() { echo -e "${GREEN}[✓]${RESET} $*"; }
warn()    { echo -e "${YELLOW}[!]${RESET} $*"; }
error()   { echo -e "${RED}[✗]${RESET} $*"; exit 1; }
ask()     { echo -e "${BOLD}${CYAN}[?]${RESET} ${BOLD}$*${RESET}"; }

[[ $EUID -ne 0 ]] && error "Please run as root: sudo bash install_mcp.sh"

echo ""
echo -e "${BOLD}╔══════════════════════════════════════════════════════╗${RESET}"
echo -e "${BOLD}║       2600net IRC MCP Server — Installer             ║${RESET}"
echo -e "${BOLD}║   Claude.ai connector for 2600net IRC                ║${RESET}"
echo -e "${BOLD}║   Written by Claude (Anthropic) for 2600net          ║${RESET}"
echo -e "${BOLD}╚══════════════════════════════════════════════════════╝${RESET}"
echo ""
echo -e "This installer is ${BOLD}independent${RESET} of the Claude IRC Bot."
echo -e "It installs to ${CYAN}/opt/claude-irc-mcp/${RESET} with its own Python venv."
echo ""

# ── Collect config ────────────────────────────────────────────────────────────
echo -e "${BOLD}── Configuration ───────────────────────────────────────${RESET}"
echo ""

ask "IRC server hostname [irc.scuttled.net]:"
read -r IRC_SERVER; IRC_SERVER="${IRC_SERVER:-irc.scuttled.net}"

ask "IRC server TLS port [6697]:"
read -r IRC_PORT; IRC_PORT="${IRC_PORT:-6697}"

ask "MCP server local port (Apache proxies to this) [8765]:"
read -r MCP_PORT; MCP_PORT="${MCP_PORT:-8765}"

ask "System user to run as [claudemcp]:"
read -r SYS_USER; SYS_USER="${SYS_USER:-claudemcp}"

echo ""
echo -e "${BOLD}── Installing … ────────────────────────────────────────${RESET}"
echo ""

# ── System user ───────────────────────────────────────────────────────────────
if id "$SYS_USER" &>/dev/null; then
    warn "User '$SYS_USER' already exists — skipping."
else
    useradd --system --no-create-home --shell /usr/sbin/nologin "$SYS_USER"
    success "Created system user: $SYS_USER"
fi

# ── Directories ───────────────────────────────────────────────────────────────
mkdir -p /opt/claude-irc-mcp
mkdir -p /etc/claude-irc-mcp
mkdir -p /var/lib/claude-irc-mcp
# /etc/claude-irc-mcp needs to be group-writable so the service user
# can create session.key on first startup
chown "root:${SYS_USER}" /etc/claude-irc-mcp
chmod 775 /etc/claude-irc-mcp
success "Created directories."

# ── Install server script ─────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cp "${SCRIPT_DIR}/irc_mcp_server.py" /opt/claude-irc-mcp/
chown "${SYS_USER}:${SYS_USER}" /opt/claude-irc-mcp/irc_mcp_server.py
chmod 750 /opt/claude-irc-mcp/irc_mcp_server.py
success "Installed irc_mcp_server.py → /opt/claude-irc-mcp/"

# ── Independent Python venv ───────────────────────────────────────────────────
# The MCP server uses its own venv — completely separate from any other
# Python environment on this machine (including the Claude IRC Bot venv).
VENV="/opt/claude-irc-mcp/venv"
if [[ -f "${VENV}/bin/python3" ]]; then
    warn "Virtual environment already exists at ${VENV} — skipping creation."
else
    info "Creating Python virtual environment at ${VENV} ..."
    python3 -m venv "$VENV"
    success "Virtual environment created."
fi

info "Installing Python packages (mcp, cryptography) ..."
"${VENV}/bin/pip" install --quiet --upgrade pip "mcp[cli]" cryptography
success "Packages installed into ${VENV}."

# ── Generate session encryption key ──────────────────────────────────────────
# Key is generated by the installer (running as root) so the service process
# never needs to write to /etc — consistent with how the IRC bot handles it.
SESSION_KEY_FILE="/etc/claude-irc-mcp/session.key"
if [[ -f "$SESSION_KEY_FILE" ]]; then
    warn "Session encryption key already exists at ${SESSION_KEY_FILE} — keeping it."
    warn "Existing sessions encrypted with the old key will still be readable."
else
    info "Generating session encryption key ..."
    "${VENV}/bin/python3" - <<PYEOF
from cryptography.fernet import Fernet
import os
key = Fernet.generate_key()
with open("$SESSION_KEY_FILE", "wb") as f:
    f.write(key)
PYEOF
    chown "${SYS_USER}:${SYS_USER}" "$SESSION_KEY_FILE"
    chmod 640 "$SESSION_KEY_FILE"
    success "Session encryption key generated: ${SESSION_KEY_FILE}"
fi

# ── Permissions ───────────────────────────────────────────────────────────────
chown -R "${SYS_USER}:${SYS_USER}" /opt/claude-irc-mcp
chown "${SYS_USER}:${SYS_USER}" /var/lib/claude-irc-mcp
chmod 750 /var/lib/claude-irc-mcp

# ── Log file ──────────────────────────────────────────────────────────────────
touch /var/log/claude-irc-mcp.log
chown "${SYS_USER}:${SYS_USER}" /var/log/claude-irc-mcp.log
success "Created log: /var/log/claude-irc-mcp.log"

# ── Config file ───────────────────────────────────────────────────────────────
cat > /etc/claude-irc-mcp/mcp_server.ini <<EOCONF
# 2600net IRC MCP Server configuration
# Owner: root:${SYS_USER}   Permissions: 640

[irc]
server      = ${IRC_SERVER}
tls_port    = ${IRC_PORT}
# Nick prefix for all MCP sessions. Quote values containing [ or ]
nick_prefix = "[ai]"

[mcp]
host        = 127.0.0.1
port        = ${MCP_PORT}
public_host = ${IRC_SERVER}
# CORS origins for browser-based clients (comma-separated or *)
# Keep as claude.ai during Anthropic audit period
cors_origins = https://claude.ai

[sessions]
idle_timeout_hours = 4

[limits]
max_sessions_global     = 500
max_sessions_per_user   = 2
connect_rate_per_minute = 5
connect_rate_per_hour   = 10
EOCONF

chown "root:${SYS_USER}" /etc/claude-irc-mcp/mcp_server.ini
chmod 640 /etc/claude-irc-mcp/mcp_server.ini
success "Written config: /etc/claude-irc-mcp/mcp_server.ini"

# Also update CONFIG_PATH in the server script to point to the new location
sed -i "s|/etc/claude-irc-bot/mcp_server.ini|/etc/claude-irc-mcp/mcp_server.ini|g" \
    /opt/claude-irc-mcp/irc_mcp_server.py

# Update SESSIONS_PATH too
sed -i "s|/var/lib/claude-irc-bot/mcp_sessions.json|/var/lib/claude-irc-mcp/mcp_sessions.json|g" \
    /opt/claude-irc-mcp/irc_mcp_server.py

# Update log path
sed -i "s|/var/log/claude-irc-mcp.log|/var/log/claude-irc-mcp.log|g" \
    /opt/claude-irc-mcp/irc_mcp_server.py

success "Patched config/data paths in server script."

# ── systemd service ───────────────────────────────────────────────────────────
cat > /etc/systemd/system/claude-irc-mcp.service <<EOSVC
[Unit]
Description=2600net IRC MCP Server
Documentation=https://github.com/astrutt/claude-irc-bot
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${SYS_USER}
Group=${SYS_USER}
ExecStart=/opt/claude-irc-mcp/venv/bin/python3 /opt/claude-irc-mcp/irc_mcp_server.py
WorkingDirectory=/opt/claude-irc-mcp
Restart=on-failure
RestartSec=15s
StartLimitIntervalSec=300
StartLimitBurst=5
TimeoutStopSec=15
StandardOutput=journal
StandardError=journal
SyslogIdentifier=claude-irc-mcp
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=full
ProtectHome=read-only

[Install]
WantedBy=multi-user.target
EOSVC

systemctl daemon-reload
systemctl enable claude-irc-mcp
success "Installed and enabled systemd service."

# ── Apache config hint ────────────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}── Apache configuration needed ─────────────────────────${RESET}"
echo ""
echo -e "Add this inside your HTTPS VirtualHost for wpm.2600.chat:"
echo ""
cat "${SCRIPT_DIR}/mcp_apache.conf"
echo ""
echo -e "Then enable modules and reload:"
echo -e "  ${BOLD}sudo a2enmod proxy proxy_http headers rewrite${RESET}"
echo -e "  ${BOLD}sudo apache2ctl configtest && sudo systemctl reload apache2${RESET}"
echo ""

# ── Done ──────────────────────────────────────────────────────────────────────
echo -e "${GREEN}${BOLD}╔══════════════════════════════════════════════════════╗${RESET}"
echo -e "${GREEN}${BOLD}║            MCP Server install complete!              ║${RESET}"
echo -e "${GREEN}${BOLD}╚══════════════════════════════════════════════════════╝${RESET}"
echo ""
echo -e "  Install:  ${CYAN}/opt/claude-irc-mcp/${RESET}"
echo -e "  Venv:     ${CYAN}/opt/claude-irc-mcp/venv/${RESET}  (independent)"
echo -e "  Config:   ${CYAN}/etc/claude-irc-mcp/mcp_server.ini${RESET}"
echo -e "  Sessions: ${CYAN}/var/lib/claude-irc-mcp/mcp_sessions.json${RESET}  (encrypted)"
echo -e "  Key:      ${CYAN}/etc/claude-irc-mcp/session.key${RESET}  (chmod 640, generated by installer)"
echo -e "  Log:      ${CYAN}/var/log/claude-irc-mcp.log${RESET}"
echo ""
echo -e "  ${BOLD}Test (foreground):${RESET}"
echo -e "  /opt/claude-irc-mcp/venv/bin/python3 /opt/claude-irc-mcp/irc_mcp_server.py"
echo ""
echo -e "  ${BOLD}Start service:${RESET}"
echo -e "  sudo systemctl start claude-irc-mcp"
echo -e "  sudo journalctl -u claude-irc-mcp -f"
echo ""
echo -e "  ${BOLD}MCP URL for Claude.ai:${RESET}"
echo -e "  ${CYAN}https://wpm.2600.chat/mcp${RESET}"
echo -e "  Settings → Connectors → Add custom connector → paste URL above"
echo ""
echo -e "  ${YELLOW}Note:${RESET} Users provide their own email when calling irc_connect."
echo -e "  ${YELLOW}Note:${RESET} Anope will email them a verification code to confirm their nick."
echo ""
